modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory
license="All rights reserved" #mandatory
 
[[mods]] #mandatory
modId="heroes_compactor_mod" #mandatory
version="0.1" #mandatory
displayName="Compactor Mod" #mandatory
logoFile="compactormod_logo.png" #optional
credits="Deja de leer estas cosas y juega 8)" #optional
authors="HeRoEs" #optional
description='''
Po eso un bloque que compacta nuggets en lingotes y lingotes en bloques
''' #mandatory